### ISSUE TITLE
Support generated IDs to avoid collisions in HTML

### ISSUE THREAD

**Issue by sdvg** [crystal-ball/svg-symbol-sprite-loader#27]
Consider this example: https://codepen.io/anon/pen/bOMQjK

There is a symbol with the ID `email` (`email.svg`) and an input field with the same ID and a connected label (`<label for="email">`).

Displaying the SVG works, but the label breaks in this example.

This could be solved by adding an option which would allow a custom function to generated the ID. For most projects it should be sufficient to provide a prefix like `icon-` to solve most conflicts. For more complex projects providing a generated UUID should also work.

I would be happy to create a PR if you like the idea :)

**Comment by DHedgecock** [comment]
Thanks for your patience while I was on vacation @sdvg

This should be available in the latest release now 🎉
